# ======================================================
# Experiment Configuration: CIFAR-10 + ResNet-18 (SGD + Cosine LR)
# ======================================================

Scenario_Name: CIFAR-10_ResNet-18_25000

Dataset:
  name: CIFAR-10
  normalization: cifar10
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 25000 #this represents the data size used for training

Model: ResNet-18

Optimizer:
  name: SGD
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: True

Scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 160
    eta_min: 0.000001

Epochs: 160
BatchSize: 128
