Scenario_Name: CIFAR-100_VGG16_25000

Dataset:
  name: CIFAR-100
  normalization: cifar100
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
    #- {name: RandomErasing, params: {p: 0.25, scale: [0.02, 0.2], ratio: [0.3, 3.3]}}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 25000

Model: VGG16

Optimizer:
  name: SGD
  params:
    lr: 0.1 #0.05
    momentum: 0.9
    weight_decay: 0.0005 # 0.0005
    nesterov: True

Scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 400   # assumes per-epoch stepping
    eta_min: 0.000001

Epochs: 400
BatchSize: 128
