# ======================================================
# Experiment Configuration: CIFAR-100 + ResNet-18 (SGD + Cosine LR) + fine-tuning (in one subset from CIFAR-100)
# ======================================================
Model_Name: CIFAR-100_ResNet-18_25000
Scenario_Name: CIFAR-100_ResNet-18_25000_Same_25000

Dataset:
  name: CIFAR-100
  normalization: cifar100
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 25000

FT_Dataset:
  name: CIFAR-100
  normalization: cifar100
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 25000
  note: same

Model: ResNet-18

Optimizers:
  - name: SGD
    strategy: FT-LL
    params:
      lr: 0.01 #0.005
      momentum: 0.9
      weight_decay: 0.0005
      nesterov: true
    Epochs: 50 #20

  - name: SGD
    strategy: FT-AL
    params:
      lr: 0.0001 #0.0005
      momentum: 0.9
      weight_decay: 0.0002 #0.0005
      nesterov: true
    Epochs: 50

  - name: SGD
    strategy: RT-AL
    params:
      lr: 0.0005
      momentum: 0.9
      weight_decay: 0.0002
      nesterov: true
    Epochs: 80

Scheduler:
  name: CosineAnnealingLR
  params:
    T_max: auto
    eta_min: 0.000001

BatchSize: 128