Scenario_Name: DeiT_CIFAR-10_Mixup_Hard_Test0

Dataset:
  name: CIFAR-10
  normalization: cifar10
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 10000 #this represents the data size used for fine-tuning

Model:
  model_name: deit_tiny_distilled_patch16_224
  img_size: 32
  patch_size: 4
  pretrained: False
  drop_path_rate: 0.05

Augmentation:   # batch-level (outside dataset)
  use_mixup: False
  mixup_alpha: 0.4
  cutmix_alpha: 0.7
  prob: 0.8
  switch_prob: 0.5
  label_smoothing: 0.05

Distillation:
  enabled: False # this represents in this case, we do not assume the stealer prepare a teacher model
  alpha: 0.5 # 0.5 means that we use the logits calculated from two heads
  tau: 2.0
  teacher_name: ResNet-18
  teacher_ckpt: "./saved_models/normal_new/CIFAR-10_ResNet-18_42/epoch_99.pth"

Optimizer:
  name: AdamW
  params:
    lr: 0.0007
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.03
    amsgrad: False

Scheduler:
  name: WarmupCosineAnnealingLR
  params:
    warmup_epochs: 10
    warmup_start_factor: 0.1
    T_max: 200
    eta_min: 0.000001

Epochs: 200
