# ======================================================
# Experiment Configuration: CIFAR-10 + ResNet-18 (SGD + Cosine LR) + fine-tuning + Adversarial Training
# ======================================================
Scenario_Name: CIFAR-10_ResNet-18_25000

Dataset:
  name: CIFAR-10
  normalization: cifar10
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 25000 #this represents the data size used for AT
  note: same

Model: ResNet-18

Attack:
  name: PGD
  eps: [0.007843, 0.015686, 0.031373]  #[2/255, 4/255, 8/255]
  steps: 10
  

Optimizer:
  name: SGD
  params:
    lr: 0.1                              # was 0.01 (fine-tune value)
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: true
  Epochs: 160    


Scheduler:
  name: CosineAnnealingLR
  params:
    T_max: auto # <-- dynamic: same as the epochs set for this strategy
    eta_min: 0.000001

BatchSize: 128
