# ======================================================
# Experiment Configuration: CIFAR-10 + ResNet-18 (SGD + Cosine LR) + fine-tuning + Adversarial Training
# ======================================================

Model_Path: 
  - /vanilla/CNN_Models/CIFAR-10_ResNet-18_25000_42_1.0
  - /vanilla/CNN_Models/CIFAR-10_ResNet-18_25000_42_0.5
  - /vanilla/CNN_Models/CIFAR-10_ResNet-18_25000_42_0.0

Dataset:
  name: CIFAR-10
  normalization: cifar10
  img_size: 32
  train_transforms:
    - {name: RandomCrop, params: {size: 32, padding: 4}}
    - {name: RandomHorizontalFlip, params: {p: 0.5}}
    - {name: ToTensor}
    - {name: Normalize}
  test_transforms:
    - {name: ToTensor}
    - {name: Normalize}
  group_size: 25000 #this represents the data size used for fine-tuning
  note: same

Model: ResNet-18

Attack:
  name: PGD
  eps: [0.007843, 0.015686, 0.031373]  #[2/255, 4/255, 8/255]
  steps: 10
  

Optimizer: # this is the optimizer used to do the adversarial training
  name: SGD
  params:
    lr: 0.003
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: true
  Epochs: 30


Scheduler:
  name: CosineAnnealingLR
  params:
    T_max: auto # <-- dynamic: same as the epochs set for this strategy
    eta_min: 0.000001

BatchSize: 128
